#pragma config(Motor,  port3,           backLeft,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           frontLeft,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           rightClawMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           backRight,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           topRight,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           tLeft,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           frontRight,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	//autonomous code goes in here. Don't delete this in case I forget. edit: MAKE SURE YOU COPY AND PASTE THE AUTONOMOUS SOMEWHERE. TAKE THIS OUT BEFORE TEST ROBO
	//all the names assigned to the motors here are wrong and some motors are missing.

	// Remove this function call once you have "real" code. I took out the line thats suppose to be under this one *edit:12/1/18
	//15 second autonomous period *12/11/18
	//Autonomous below is suppose to move towards lower flag come back,turn, and go up a platform(go straight)
	
	motor[frontLeft] = 127;
	motor[frontRight] = 127;
	motor[backLeft] = 127;
	motor[backRight] = 127;
	wait1Msec(1500);
	motor[frontLeft] = 0;
	motor[frontRight] = 0;
	motor[backLeft] = 0;
	motor[backRight] = 0;
	wait1Msec(500);
	motor[frontLeft] = 127;
	motor[frontRight] = 127;
	motor[backLeft] = 127;
	motor[backRight] = 127;
	wait1Msec(2000);
	motor[frontLeft] = 127;
	motor[frontRight] = -127;
	motor[backLeft] = 127;
	motor[backRight] = -127;
	wait1Msec(600);
	motor[frontLeft] = 127;
	motor[frontRight] = 127;
	motor[backLeft] = 127;
	motor[backRight] = 127;
	wait1Msec(1250);

}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, INSIDE THE WHILE LOOP
	while (true)
	{
		//Basic movement controls code here. This code specifically is tank control. FULLY FUNCTIONAL 11/19/18
		//Left side
		motor[frontLeft] = vexRT[Ch2];
		motor[backLeft] = vexRT[Ch2];
		//Right side
		motor[frontRight] = vexRT[Ch3];
		motor[backRight] = vexRT[Ch3];
		// If statement is for shoulder buttons.5u,5d and 6u,6d
		//UPDATE 12/11/18 Use 5U and 6U aka topleft and topright shoulder buttons

		if(vexRT[Btn8D] == 1)
		{
			motor[frontLeft] = 127;
			motor[frontRight] = 127;
			motor[backLeft] = 127;
			motor[backRight] = 127;
			wait1Msec(1500);
			motor[frontLeft] = 0;
			motor[frontRight] = 0;
			motor[backLeft] = 0;
			motor[backRight] = 0;
			wait1Msec(500);
			} else {
			motor[frontLeft] = 0;
			motor[frontRight] = 0;
			motor[backLeft] = 0;
			motor[backRight] = 0;
		}



		//if you modify the code it just disables one button and makes the other work.
		{
			if(vexRT[Btn5U] == 1)
			{
				motor[tLeft] = -127;
				motor[topRight] = -127;
			}
			else if(vexRT[Btn6U] == 1)
				motor[tLeft] = 127;
			{
				motor[topRight] = 127;
			}
			else{
				motor[tLeft] = 0;
				motor[topRight] = 0;
			}
		}
	}
}
