#pragma config(Motor,  port2,           topLeft,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           backLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           frontRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           backRight,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           topRight,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           leftClawMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rightClawMotor, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	//autonomous code goes in here. Don't delete this in case I forget. edit: MAKE SURE YOU COPY AND PASTE THE AUTONOMOUS SOMEWHERE. TAKE THIS OUT BEFORE TEST ROBO
	//all the names assigned to the motors here are wrong and some motors are missing.

	AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
	
	//Autonomous below is suppose to move foward, stop, and move back.
	motor[frontLeft] = 127;
	motor[frontRight] = 127;
	motor[backLeft] = 127;
	motor[backRight] = 127;
	wait1Msec(500);
	motor[frontLeft] = -127;
	motor[frontRight] = -127;
	motor[backLeft] = -127;
	motor[backRight] = -127;
	wait1Msec(1500);

}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, INSIDE THE WHILE LOOP
	while (true)
	{ //The If statement here is for a "claw".
		if(vexRT[Btn5U] == 1){
			motor[leftClawMotor] = 127;
			motor[rightClawMotor] = 127;
		}
		else if(vexRT[Btn6U] == 1){
			motor[leftClawMotor] = -127;
			motor[rightClawMotor] = 127;
		}
		else{
			motor[leftClawMotor] = 0;
			motor[rightClawMotor] = 0;
		}
		//Basic movement controls code here. This code specifically is tank control. 10/30/18
		//Left side. UPDATE: Left motors works
		motor[frontLeft] = vexRT[Ch3];
		motor[backLeft] = vexRT[Ch3];
		//Right side UPDATE: Back right motor is not secure and front right is dead.
		motor[frontRight] = vexRT[Ch2];
		motor[backRight] = vexRT[Ch2];
		// If statement is for shoulder buttons.5u,5d and 6u,6d
		{
			if(vexRT[Btn5U] == 1){
				motor[topLeft] = -127;
				motor[topRight] = -127;
			}
			else if(vexRT[Btn6U] == 1){
				motor[topLeft] = 127;
				motor[topRight] = 127;
			}
			else{
				motor[topLeft] = 0;
				motor[topRight] = 0;
			}
		}
	}
}
